config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :users do
    resources :groups, only: [:index, :new, :create, :destroy] do
      resources :expenses, only: [:index, :new, :create, :destroy] 
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#home'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  ROLS = %w[admin member].freeze

  ROLS.each do |rol|
    define_method("#{rol}?") do
      role == rol
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :role)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:name, :email, :password, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    user_groups_path(current_user)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @group = Group.includes(:expenses).find(params[:group_id])
    @expenses = @group.expenses.where(author: @user).order(created_at: :desc)
    @total_expense = @group.expenses.sum(:amount)
  end

  def new
    @user = current_user
    @group = Group.find(params[:group_id])
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user
    @expense.group = Group.find(params[:group_id])

    if @expense.save
      flash[:notice] = 'Transaction successfully created'
      redirect_to user_group_expenses_path(current_user, @expense.group)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to new_user_group_expense_path(current_user, @expense.group)
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    flash[:notice] = 'Transaction deleted successfully'
    redirect_to user_group_expenses_path
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @groups = Group.where(user: @user)
    @expenses = Expense.where(author: @user)
    @total_expense = @expenses.sum(:amount)
  end

  def new
    @image_names = Dir.glob('app/assets/images/icons/*.png')
    @group = Group.new
    @user = current_user
  end

  def create
    @user = current_user
    @group = Group.new(group_params)
    @group.user_id = @user.id
    @image_names = Dir.glob('app/assets/images/icons/*.png')

    if @group.save
      flash[:notice] = 'Category created successfully'
      redirect_to user_groups_path(@user)
    else
      puts @group.errors.full_messages
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Category deleted successfully'
    redirect_to user_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_groups_root
    if current_user
      redirect_to user_groups_path(current_user)
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/index.html.erb
<div class="top-container">
  <header>    
    <%= link_to image_tag('rowback.svg', class: 'btn-back'), user_groups_path(@user), class: 'back' %>
    <h2>Transactions</h2>    
  </header>
  <main class="devise">
    <div class="items-container">
      <div class="group-item">
        <%= image_tag "icons/#{@group.icon}", alt: "category icon #{@group.name}", class: 'img-icon' %>
        <p>Total amount for <%= @group.name %>: </p> <span> <% if defined?(@total_expense) %> <%= number_to_currency(@total_expense, precision: 2) %> <% else %> <%= number_to_currency(0.00, precision: 2) %> <% end %> </span>
      </div>
      <% if @expenses.blank? %>
        <p class="text">There are no transactions yet, please add new.</p>
      <% else %>
          <div class='items-container'>
            <% @expenses.each do |expense| %>
              <div class='group-item'>
                <p><%= expense.name %></p>
                <p ><%= expense.updated_at.strftime('%Y/%m/%d') %></p>
                <p ><%= number_to_currency(expense.amount, precision: 2) %></p>
                <%= link_to "Delete", user_group_expense_path(@user, @group, expense), data: { turbo_method: :delete }, confirm: 'Are you sure?', class: 'lnk-delete' %>
              </div>
            <% end %>
          <div >
      <% end %>
    </div>
  </main>
</div>
<footer>
  <%= button_to 'Add new transaction', new_user_group_expense_path, method: :get, class: 'f-button btn' %>
  <%= @user.name %>
</footer>

app/views/expenses/new.html.erb
<div class="top-container">
  <header>
  <%= link_to image_tag('rowback.svg', class: 'btn-back'), :back, class: 'back' %>
  <h2>New Transaction</h2>
  </header>

  <main class="devise">
    <h3 class='title'>New transaction for <%= @group.name %> category</h3>    
    <%= form_with model: @expense, url: user_group_expenses_path(@user, @group) do |f| %>
      <%- if @expense.errors.any? %>
        <div class="alert">
          Something went wrong
        </div>
      <% end %>
      <div class="fields">
        <div class="field">        
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Transaction name' %>
          <%- if @expense.errors[:name].any? %>
            <div class="alert">
              <%= @expense.errors[:name].first %>
            </div>
          <% end %>
        </div>

        <div class="field">
          <%= f.number_field :amount, autocomplete: "amount", placeholder: 'Transaction amount', step: '0.01' %>
          <%- if @expense.errors[:amount].any? %>
            <div class='alert' >
              <%= @expense.errors[:amount].first %>
            </div>
          <% end %>
        </div>
        <footer class="onbody">
          <div class="actions">
            <%= f.submit "Save transaction", class: "f-button btn" %>
          </div>
        </footer>
      </div>      
    <% end %>
  </main>

</div>
<footer>
  <%= @user.name %>
</footer>

app/views/groups/index.html.erb
<div class="top-container">
  <header>
    <%= link_to image_tag('rowback.svg', class: 'btn-back'), :root, class: 'back' %>
    <h2>Categories</h2>
  </header>

  <main class='devise'>
    <% if @groups.blank? %>
      <h3>Please add category to start</h3>
    <% else %>
      <div class="items-container">
        <%- if @total_expense.blank? %>
          <h3>Total cost: <%= number_to_currency(0.00, precision: 2) %></h3>
        <% else %>
          <h3>Total cost: <%= number_to_currency(@total_expense, precision: 2) %></h3>
        <% end %>
        <% @groups.each do |group| %>
          <% expenses_group = group.expenses %>
            <div class="group-item">
              <%= image_tag "icons/#{group.icon}", alt: "category icon #{group.name}", class: 'img-icon' %>
              <%= button_to user_group_expenses_path(current_user, group), method: :get, class: 'btn-group' do %>
                <p class='group-name'><%= group.name %></p>
              <% end %>
              <% if expenses_group.any? %>
                <p><%= number_to_currency(expenses_group.sum(:amount), precision: 2) %></p>
              <% else %>
                <p>0.00</p>
              <% end %>        
              <%= link_to "Delete", user_group_path(current_user, group), data: { turbo_method: :delete }, confirm: 'Are ypu sure?', class: 'lnk-delete' %>
            </div>
        <% end %>
      </div>
    <% end %>
  </main>

</div>


<footer>
  <%= button_to 'Add new category', new_user_group_path, method: :get, class: 'f-button btn' %>
</footer>

app/views/groups/new.html.erb
<div class="top-container">
  <header>
    <%= link_to image_tag('rowback.svg', class: 'btn-back'), user_groups_path(current_user), class: 'back' %>
    <h2>Categories</h2>
  </header>

  <main class='devise'>
    <%= form_with model: @group, url: user_groups_path(@user) do |f| %>
    <%- if @group.errors.any? %>
      <div class="alert">
        Something went wrong
      </div>
    <% end %>
      <div class="fields">
        <div class="field">        
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Category name' %>
          <%- if @group.errors[:name].any? %>
            <div class="alert">
              <%= @group.errors[:name].first %>
            </div>
          <% end %>
        </div>
      <h3>Select icon:</h3>
      <div class="icons">
        <% @image_names.each do |image_name| %>
          <div class="icon-item">
            <%= f.radio_button :icon, image_name.split('/').last, id: image_name %>
            <%= f.label image_name.split('/').last, image_tag("icons/#{image_name.split('/').last}", class: 'img-icon') %>
          </div>
        <% end %>
        <% if @group.errors[:icon].any? %>
          <div class="alert">
            <%= @group.errors[:icon].first %>
          </div>
        <% end %>
      </div>
      </div>
      <footer>
        <%= f.submit "Save category", class: 'f-button btn' %>
      </footer>
    <% end %>
  </main>
</div>
<footer>
  <%= @user.name %>
</footer>

app/views/home/index.html.erb
<h1>RENDER IS OK!</h1>
<p>Good whats is the next step.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Pennywise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">      
      <%= yield %>
    </div>
  </body>
</html>

app/views/navigation/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to('Home', root_path, class: 'button') %>      
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <div class="navbar-item ">
                <%= current_user.name %>
                <%= button_to('Logout', destroy_user_session_path, method: :delete, class: 'button') %>
            </div>
          <% else %>
            <%= link_to('Sign up', new_user_registration_path, class: 'button') %>
            <%= link_to('Log in', new_user_session_path, class: 'button') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<header >  
  <h1>Pennywise</h1>
  <p class='message'>An app about your spents</p>
</header>

<main class='main-home'>
<% if user_signed_in? %>
  <p class='user-name'>Welcome <%= current_user.name %></p>
  <%= link_to 'Enter', user_groups_path(current_user), class: 'lnk-enter' %>
<% end %>
  <img src="<%= asset_path('pennywise.png') %>" alt="logo pennywise" class="logo">
</main>
<footer>
  <% if user_signed_in? %>
      <div class="logout">
          
          <%= button_to('Logout', destroy_user_session_path, method: :delete, class: 'f-button btn') %>
      </div>
    <% else %>
      <%= link_to('Log in', new_user_session_path, class: 'f-button') %>
      <%= link_to('Sign up', new_user_registration_path, class: 'f-button') %>
  <% end %>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>